### ISSUE TITLE
Ivy.xml - Should we use default user cache or each project have its own cache directory?

### ISSUE THREAD

**Issue by pdragosh** [att/XACML#11]
It seems that using the default user cache can bring in conflicts if the user has more recent versions of libraries. Eclipse Ivy seems to default to using the latest library available, rather than the library specified. This came about with commons-code v1.6 being needed within the projects, but v1.8 was in the cache due to another non-XACML project. Unfortunately, v1.8 changed a method and removed an exception being thrown. This causes non-compilation of Xacml-PAP-ADMIN.

Any thoughts?

**Comment by invious** [comment]
any fix for this? how to configure ivy dependencies

**Comment by pdragosh** [comment]
I have switched from using ivy to Maven. Haven't pushed the changes for that project yet.

**Comment by invious** [comment]
I created an xml file with
```
<ivy-module version="2.0">
	<info organisation="org.apache" module="hello-ivy"/>
	<dependencies>
		<dependency org="commons-logging" name="commons-logging" rev="1.1.1"/>
		<dependency org="com.vaadin" name="vaadin" rev="6.8.18"/>
	</dependencies>
</ivy-module>
```

but com.vaadin.ui.UI is still not resolving and I can't seem to find a dependency for it

**Comment by invious** [comment]
I can't find oasis.names.tc.xacml._3_0.core anywhere on the internet, what do I need for it to resolve?

**Comment by invious** [comment]
finally got all the Xs to go away
had to install Vaadin plug-in
create Vaadin project
consolidate allll the src files into one
rename all the imports using replace all from com.whaterver to main.com.whaetver
had to have ivy plugin installed
and had to hunt down the ivy repo urls for a bunch of imports
ended up adding
```
		<dependency org="commons-logging" name="commons-logging" rev="1.1.1"/>
		<dependency org="org.eclipse.persistence" name="eclipselink" rev="2.6.4"/>
		<dependency org="org.eclipse.jgit" name="org.eclipse.jgit" rev="4.7.0.201704051617-r"/>
		<dependency org="org.apache.commons" name="commons-compress" rev="1.13"/>
		<dependency org="com.fasterxml.jackson.core" name="jackson-databind" rev="2.9.0.pr2"/>
		<dependency org="au.com.bytecode" name="opencsv" rev="2.4"/>
		<dependency org="org.apache.velocity" name="velocity" rev="1.7"/>
``` to the ivy.xml generated by the vaadin plug in.

no more ❌ , how do i ⏯

**Comment by pdragosh** [comment]
We won't be supporting Ivy anymore. We are using Maven.
