### ISSUE TITLE
Cannot run XACML-PAP-ADMIN and XACML-PAP-REST

### ISSUE THREAD

**Issue by vasicvuk** [att/XACML#43]
When running XACML-PAP-ADMIN and XACML-PAP-REST on Windows 10. Java jdk1.8.0_144. I get next error:

Error scanning entry META-INF/versions/9/module-info.class from jar file:///D:/Projects/XACML/XACML-PAP-ADMIN/target/xacml-pap-admin-2.0.0-SNAPSHOT/WEB-INF/lib/log4j-api-2.11.0.jar

**Comment by flightprofiler** [comment]
When I try to do "mvn clean install" on windows, I get this error, " ATT XACML 2.0.0-SNAPSHOT ........................... FAILURE".
I really appreciate if you can guide me how to get rid of this error :(

**Comment by pdragosh** [comment]
Seems like an issue with jetty trying to finding log4j - I just upgraded to 9.4 which resolved it.
