### ISSUE TITLE
issue with running mvn jetty:run-war

### ISSUE THREAD

**Issue by maryamdavari** [att/XACML#45]
Hi all,  

Java 1.8 is alreday installed and apache-maven-3.5.4. But when I try to run "mvn jetty:run-war" in this path XACMLEngine/XACML-master/XACML-PAP-REST:
I get the following errors: 
[ERROR] Failed to execute goal on project xacml-pap-rest: Could not resolve dependencies for project com.att.research.xacml:xacml-pap-rest:war:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.att.research.xacml:xacml:jar:2.0.0-SNAPSHOT, com.att.research.xacml:xacml-pdp:jar:2.0.0-SNAPSHOT, com.att.research.xacml:xacml-rest:jar:2.0.0-SNAPSHOT: Could not find artifact com.att.research.xacml:xacml:jar:2.0.0-SNAPSHOT -> [Help 1]

I am just wondering to know if I need an extra java plugin.
I appreciate your help. 

Thanks

**Comment by pdragosh** [comment]
Doesn't look like you compiled the code first:
mvn clean install
