### ISSUE TITLE
issue containerizing app with docker

### ISSUE THREAD

**Issue by mcgingras** [att/XACML#52]
I am trying to containerize this application using docker, but have been running into a few issues with the first step: running mvn clean install on the root to generate the dependancies.

I have been getting the issue 

`
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
`

so I am assuming it is missing a gpg key in the container, but I am not exactly sure what this is even needed for or how to generate one within the container. Any help would be appreciated here.

Thanks,
Michael

**Comment by pdragosh** [comment]
Shouldn't be getting that off the master branch - I put that into a profile as the gpg is only relevant for releasing the jar's to maven sonatype repo.

**Comment by mcgingras** [comment]
so you're suggesting I might be on the wrong branch? Not sure how that might have happened but I will try on master.
