### ISSUE TITLE
How to run from command line without mvn jetty?

### ISSUE THREAD

**Issue by mcgingras** [att/XACML#53]
Is there a way to run this project without relying on mvn jetty? I am trying to package it into a container without using maven (so I'd like to launch the apps from the command line using something like java -jar) but I am not able to get it working. Any help would be appreciated. I've tried packaging the war and using something like jetty-war to launch it, but that also does not work.

**Comment by pdragosh** [comment]
Building embedded jetty is possible. Since war files are produced, you should also be able to copy the war files into an installation of jetty, tomcat, wildfly etc.

**Comment by mcgingras** [comment]
For whatever reason that is not working for me. Perhaps I am trying the wrong way. I am deploying the war as root.jar to the webapps dir of a jetty distro, but it fails to do behave as it does when running mvn jetty:run-war.

Thanks
