### ISSUE TITLE
http://localhost:8080/pdp/ gives HTTP ERROR 400

### ISSUE THREAD

**Issue by maryamdavari** [att/XACML#54]
When I run 'mvn jetty:run-war' in the XACML-PDP-REST subdirectory, this error is shown:
HTTP ERROR 400

Problem accessing /pdp/. Reason:

    type not 'config' or 'hb'

Powered by Jetty:// 9.4.12.v20180830

I am just wondering to know how I can fix this issue. 
Thanks

**Comment by pdragosh** [comment]
There's nothing to fix, you need to add either one of those type parameters to the URI.
For example:
http://localhost:8080/pdp/?type=config
